[tool.poetry]
name = "pcompress"
version = "0.1.0"
description = ""
authors = ["Max Fan <root@max.fan>"]

[tool.poetry.dependencies]
python = ">=3.7"
gerrychain = "^0.2.17"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
